# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f41f144c88b12cec40b089ac0ff02ba2186300ade09fe10fd1471b59c674e81d53b5ac724db99345256b548369dfdc2ea9d4a00a9268b731087c12c9c002cfc

test:
  secret_key_base: 4fbe1adf9ffa93548dc953004df1798e187501d4c33de29110d1331ac9ef5346186a67626c50284996a8f21092b67742d1d4164ed42ac428d89417f5bd376f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
